# Action for running tests
# This file has been automatically created.
# To recreate it you can run this command
# ./console generate:test-action --plugin="MarketingCampaignsReporting" --php-versions="7.2,8.4" --schedule-cron="55 2 * * 6"

name: Plugin MarketingCampaignsReporting Tests

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - '**.x-dev'
  workflow_dispatch:
  schedule:
  - cron: "55 2 * * 6"

permissions:
  actions: read
  checks: none
  contents: read
  deployments: none
  issues: read
  packages: none
  pull-requests: read
  repository-projects: none
  security-events: none
  statuses: none

concurrency:
  group: php-${{ github.ref }}
  cancel-in-progress: true

jobs:
  PluginTests:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        php: [ '7.2', '8.4' ]
        engine: [ 'Mysql', 'Mariadb' ]
        adapter: [ 'PDO_MYSQL', 'MYSQLI' ]
        target: ['minimum_required_matomo', 'maximum_supported_matomo']
        exclude:
          - php: '7.2'
            engine: 'Mariadb'
          - php: '8.2'
            engine: 'Mysql'
          - php: '8.4'
            engine: 'Mariadb'
          - php: '7.2'
            adapter: 'MYSQLI'
          - php: '8.2'
            adapter: 'MYSQLI'
          - php: '8.4'
            adapter: 'PDO_MYSQL'
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
          persist-credentials: false
      - name: Install package ripgrep
        run: sudo apt-get install ripgrep
      - name: Run tests
        uses: matomo-org/github-action-tests@main
        with:
          plugin-name: 'MarketingCampaignsReporting'
          mysql-driver: ${{ matrix.adapter }}
          mysql-engine: ${{ matrix.engine }}
          php-version: ${{ matrix.php }}
          test-type: 'PluginTests'
          matomo-test-branch: ${{ matrix.target }}
          artifacts-pass: ${{ secrets.ARTIFACTS_PASS }}
          upload-artifacts: ${{ matrix.php == '7.2' && matrix.target == 'maximum_supported_matomo' }}
  UI:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
          persist-credentials: false
      - name: running tests
        uses: matomo-org/github-action-tests@main
        with:
          plugin-name: 'MarketingCampaignsReporting'
          matomo-test-branch: 'maximum_supported_matomo'
          test-type: 'UI'
          php-version: '7.2'
          node-version: '16'
          artifacts-pass: ${{ secrets.ARTIFACTS_PASS }}
          upload-artifacts: true
